# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vector_service_pb2 as vector__service__pb2


class EmbeddingServiceStub(object):
    """── Embedding Service ─────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateEmbedding = channel.unary_unary(
                '/vectorservice.EmbeddingService/GenerateEmbedding',
                request_serializer=vector__service__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=vector__service__pb2.EmbeddingResponse.FromString,
                )
        self.GenerateEmbeddingBatch = channel.unary_unary(
                '/vectorservice.EmbeddingService/GenerateEmbeddingBatch',
                request_serializer=vector__service__pb2.EmbeddingBatchRequest.SerializeToString,
                response_deserializer=vector__service__pb2.EmbeddingBatchResponse.FromString,
                )


class EmbeddingServiceServicer(object):
    """── Embedding Service ─────────────────────────────────────────────────────────

    """

    def GenerateEmbedding(self, request, context):
        """Generate a vector embedding from a text string
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEmbeddingBatch(self, request, context):
        """Generate embeddings for a batch of texts (used by Spark job)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbedding,
                    request_deserializer=vector__service__pb2.EmbeddingRequest.FromString,
                    response_serializer=vector__service__pb2.EmbeddingResponse.SerializeToString,
            ),
            'GenerateEmbeddingBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbeddingBatch,
                    request_deserializer=vector__service__pb2.EmbeddingBatchRequest.FromString,
                    response_serializer=vector__service__pb2.EmbeddingBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vectorservice.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """── Embedding Service ─────────────────────────────────────────────────────────

    """

    @staticmethod
    def GenerateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vectorservice.EmbeddingService/GenerateEmbedding',
            vector__service__pb2.EmbeddingRequest.SerializeToString,
            vector__service__pb2.EmbeddingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateEmbeddingBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vectorservice.EmbeddingService/GenerateEmbeddingBatch',
            vector__service__pb2.EmbeddingBatchRequest.SerializeToString,
            vector__service__pb2.EmbeddingBatchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class IndexServiceStub(object):
    """── Index Service ─────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchIndex = channel.unary_unary(
                '/vectorservice.IndexService/SearchIndex',
                request_serializer=vector__service__pb2.SearchRequest.SerializeToString,
                response_deserializer=vector__service__pb2.SearchResponse.FromString,
                )
        self.GetIndexInfo = channel.unary_unary(
                '/vectorservice.IndexService/GetIndexInfo',
                request_serializer=vector__service__pb2.IndexInfoRequest.SerializeToString,
                response_deserializer=vector__service__pb2.IndexInfoResponse.FromString,
                )
        self.ReloadIndex = channel.unary_unary(
                '/vectorservice.IndexService/ReloadIndex',
                request_serializer=vector__service__pb2.ReloadIndexRequest.SerializeToString,
                response_deserializer=vector__service__pb2.ReloadIndexResponse.FromString,
                )


class IndexServiceServicer(object):
    """── Index Service ─────────────────────────────────────────────────────────────

    """

    def SearchIndex(self, request, context):
        """ANN search: find top-K nearest neighbors for a query vector
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexInfo(self, request, context):
        """Return index statistics and health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadIndex(self, request, context):
        """Trigger a hot reload of the FAISS index from disk (blue-green swap)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchIndex,
                    request_deserializer=vector__service__pb2.SearchRequest.FromString,
                    response_serializer=vector__service__pb2.SearchResponse.SerializeToString,
            ),
            'GetIndexInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexInfo,
                    request_deserializer=vector__service__pb2.IndexInfoRequest.FromString,
                    response_serializer=vector__service__pb2.IndexInfoResponse.SerializeToString,
            ),
            'ReloadIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadIndex,
                    request_deserializer=vector__service__pb2.ReloadIndexRequest.FromString,
                    response_serializer=vector__service__pb2.ReloadIndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vectorservice.IndexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IndexService(object):
    """── Index Service ─────────────────────────────────────────────────────────────

    """

    @staticmethod
    def SearchIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vectorservice.IndexService/SearchIndex',
            vector__service__pb2.SearchRequest.SerializeToString,
            vector__service__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIndexInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vectorservice.IndexService/GetIndexInfo',
            vector__service__pb2.IndexInfoRequest.SerializeToString,
            vector__service__pb2.IndexInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReloadIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vectorservice.IndexService/ReloadIndex',
            vector__service__pb2.ReloadIndexRequest.SerializeToString,
            vector__service__pb2.ReloadIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
